scss_files: 'source/stylesheets/**/*.scss'

exclude: 'source/stylesheets/_normalize.scss'

linters:
  BorderZero:
    enabled: false

  Indentation:
    severity: warning
    width: 2

  LeadingZero:
    enabled: false

  PropertySortOrder:
    order: smacss

  SelectorFormat:
    convention: hyphenated_BEM
